-- make a kind of IDEA-like terminal...
vim.keymap.set('n', '<C-t>', ':FloatermNew --height=0.3 --width=1.0 --wintype=floating --name=Terminal --position=bottom<CR>')

-- make a commands tha tallows to reenter the tarminal...
vim.keymap.set('n', '<C-r>', ':FloatermToggle<CR>')
